language: csharp
mono:
  - latest

solution: PCLExt.AppDomain.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PCLExt.AppDomain.sln
  
script:
  - xbuild /p:Configuration=Release PCLExt.AppDomain.sln
  - xbuild /p:Configuration=Debug PCLExt.AppDomain.sln

notifications:
  email:
    on_success: always
